export const PATHS = {
    MANAGE: {
        HOME: "/",
        DASHBOARD: "dashboard",
        MENU: "menu",
        STAFFS: "staffs",
        ORDERS: "orders",
        ATTENDANCE: "attendance",
        ATTACHMENTS: "attachments",
        AVAILIBILITIES: "availibilities",
        TABLES: "tables",
        INGREDIENTS: "ingredients",
        SHIFTS: "shifts",
        ROLE: "role",
        PERMISSION: "permission",
        ACCOUNT_PERMISSION: "account-permission",
        BOOKING_MANAGEMENT: "booking-management",
        RECRUITMENT: "recruitment",
        APPLY_RECRUITMENT: "apply-recruitment",
    },
    PUBLIC: {
        MENU: "menu-public",
        BOOKING: "booking",
        KITCHEN: "kitchen",
        PROFILE: "profile",
        TICKET: "ticket",
        RECRUITMENT: "recruitment",
    },
};
