const urls = {
    auth: "auth",
    accounts: "accounts",
    login: "login",
    menuItems: "menu-items",
    api: "api",
    roles: "roles",
    permissions: "permissions",
    files: "files",
    upload: "upload",
    employees: "employees",
    shifts: "shifts",
    availibilities: "availibilities",
    orders: "orders",
    orderitems: "order-items",
    ingredients: "ingredients",
    attendances: "attendances",
    customers: "customers",
    tables: "tables",
};
export default urls;
