const urls = {
    auth: "auth",
    accounts: "accounts",
    login: "login",
    menuItems: "menu-items",
    api: "api",
    roles: "roles",
    permissions: "permissions",
    files: "files",
    upload: "upload",
    employees: "employees",
    shifts: "shifts",
    availibilities: "availibilities",
    orders: "orders",
    orderitems: "order-items",
    ingredients: "ingredients",
    attendances: "attendances",
    customers: "customers",
    tables: "tables",
    import_excel: "import-excel",
    table: "table",
    order: "order",
    bookings: "bookings",
    shifts_chedules: "shifts-chedules",
    tickets: "tickets",
    recruitments: "recruitments",
    apply_recruitment: "apply-recruitments",
    stats: "stats",
    salary: "salary",
    all: "all",
    revenue: "revenue",
};
export default urls;
